#!/usr/bin/env python3
"""
Regenerates embedded_payload.h from ../source/table.h and ../source/table.c.

This is the Unix installer's equivalent of installer.rc's RCDATA embeds on
Windows: instead of a resource compiler, we just dump the two source files
as byte arrays into a C header that installer_unix.cpp #includes directly.
We embed *source* (table.h + table.c), not a prebuilt .a - the installer
compiles libtable.a locally at install time with the host's own cc/clang,
which sidesteps glibc/libc++ ABI mismatches that a prebuilt Linux/macOS
binary could hit on a machine we didn't build it on.

Run this any time source/table.h or source/table.c changes, before
build_installer_unix.sh.
"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent
SRC_DIR = ROOT.parent / "source"
OUT_PATH = ROOT / "embedded_payload.h"


def emit_array(name: str, data: bytes) -> str:
    lines = [f"static const unsigned char {name}[] = {{"]
    row = []
    for i, b in enumerate(data):
        row.append(f"0x{b:02x},")
        if len(row) == 20:
            lines.append("    " + " ".join(row))
            row = []
    if row:
        lines.append("    " + " ".join(row))
    lines.append("};")
    lines.append(f"static const unsigned long {name}_len = {len(data)}UL;")
    return "\n".join(lines)


def main() -> None:
    header_bytes = (SRC_DIR / "table.h").read_bytes()
    source_bytes = (SRC_DIR / "table.c").read_bytes()

    out = []
    out.append("// AUTO-GENERATED by generate_embedded_payload.py - do not edit by hand.")
    out.append("// Regenerate after any change to source/table.h or source/table.c.")
    out.append("#pragma once")
    out.append("")
    out.append(emit_array("g_TableH", header_bytes))
    out.append("")
    out.append(emit_array("g_TableC", source_bytes))
    out.append("")

    OUT_PATH.write_text("\n".join(out), encoding="utf-8")
    print(f"Wrote {OUT_PATH} ({len(header_bytes)} bytes header, {len(source_bytes)} bytes source)")


if __name__ == "__main__":
    main()
